// Auto-generated by scripts/generate-starter-guides.mjs — bundled default content
// shown to every visitor before they generate or submit their own guides.
export const STARTER_GUIDES = [
  {
    "title": "How to Bake Artisan Sourdough Bread from Scratch",
    "summary": "Master the fundamentals of baking rustic, naturally leavened sourdough bread with an open, airy crumb and blistered crust. This guide walks you through every stage from mixing your levain to the final bake in a Dutch oven.",
    "difficulty": "Intermediate",
    "estimatedTime": "24 hours (active time: ~1.5 hours)",
    "tools": [
      "Digital kitchen scale",
      "Active sourdough starter",
      "Unbleached bread flour and whole wheat flour",
      "Cast iron Dutch oven with lid",
      "Banneton proofing basket (or towel-lined bowl)",
      "Baker's lame or razor blade",
      "Parchment paper"
    ],
    "steps": [
      {
        "id": 1,
        "title": "Feed and Build the Levain",
        "content": "Combine 20g of mature sourdough starter with 50g of lukewarm water (around 78°F/26°C), 25g of unbleached bread flour, and 25g of whole wheat flour in a clean jar. Stir thoroughly until no dry bits remain, mark the level on the jar with a rubber band, and loosely cover the top. Allow it to sit in a warm spot for 4 to 6 hours until it has doubled in volume and appears bubbly and domed on top.",
        "tip": "Test readiness by dropping a teaspoon of levain into a cup of room-temperature water; if it floats, it is ready to bake with.",
        "codeSnippet": null
      },
      {
        "id": 2,
        "title": "Autolyse the Flour and Water",
        "content": "In a large mixing bowl, whisk together 450g of bread flour and 50g of whole wheat flour. Add 350g of warm water (around 80°F/27°C) and stir using your hands or a spatula until all flour is hydrated into a shaggy dough. Cover the bowl with a damp towel and let it rest undisturbed for 45 to 60 minutes to develop enzymatic activity and initial gluten structure.",
        "tip": "Do not skip the autolyse phase, as it dramatically reduces the amount of physical kneading required later.",
        "codeSnippet": null,
        "image": "https://images.unsplash.com/photo-1495521818451-c2b87c65bffb?w=700&h=400&fit=crop&auto=format"
      },
      {
        "id": 3,
        "title": "Incorporate Levain and Salt",
        "content": "Spread 100g of your active levain over the autolysed dough and use your fingers to dimple and fold it evenly into the mixture. Sprinkle 10g of fine sea salt along with an optional 10g splash of warm water over the top. Use the 'pinch and fold' method—pinching sections of dough between your fingers and folding the edges over—for 3 to 5 minutes until the dough becomes cohesive and smooth.",
        "tip": "Salt tightens the gluten network and slows yeast fermentation, so ensure it is evenly distributed throughout.",
        "codeSnippet": null
      },
      {
        "id": 4,
        "title": "Perform Stretch and Folds During Bulk Fermentation",
        "content": "Cover the dough and let it rest at room temperature (75°F–78°F is ideal) for a total bulk fermentation time of 3 to 4 hours. During the first two hours, perform four sets of stretch-and-folds spaced 30 minutes apart. To do a fold, wet your hands, pull one quadrant of dough upward until you feel tension, fold it over the top, rotate the bowl 90 degrees, and repeat for all four corners.",
        "tip": "Handle the dough more gently with each subsequent set of folds to avoid degassing accumulated fermentation bubbles.",
        "codeSnippet": null
      },
      {
        "id": 5,
        "title": "Preshape and Rest the Dough",
        "content": "Gently tip the dough out onto an unfloured work surface using a bowl scraper. Use a bench knife and your free hand to pull and turn the dough against the counter in circular motions, building surface tension until a smooth, round ball forms. Leave the dough uncovered on the counter for 20 to 30 minutes to relax its gluten structure.",
        "tip": "If the dough spreads flat like a pancake during the rest, it lacks sufficient gluten development or was over-fermented.",
        "codeSnippet": null
      },
      {
        "id": 6,
        "title": "Final Shape and Transfer to Banneton",
        "content": "Dust the top of the dough lightly with flour, flip it over, and fold the bottom third up toward the center, followed by the left and right sides, rolling the cylinder down into a tight log (batard) or sphere (boule). Dust a banneton basket heavily with rice flour to prevent sticking. Scoop up the shaped dough with your bench knife and deposit it seam-side-up into the prepared basket.",
        "tip": "Rice flour is gluten-free and will not absorb moisture, making it far superior to regular wheat flour for dusting bannetons.",
        "codeSnippet": null
      },
      {
        "id": 7,
        "title": "Cold Retard (Overnight Proofing)",
        "content": "Slip the banneton inside a plastic bag or cover it with a reusable shower cap to trap humidity and keep the dough from drying out. Transfer the basket directly to the refrigerator (set between 36°F and 39°F / 2°C–4°C) for 12 to 16 hours. This cold fermentation slows yeast activity while allowing bacteria to produce lactic and acetic acids, deepening the sourdough flavor.",
        "tip": "Cold dough is substantially firmer than warm dough, making it much easier to score cleanly before baking.",
        "codeSnippet": null
      },
      {
        "id": 8,
        "title": "Preheat, Score, and Bake",
        "content": "Place your Dutch oven with the lid on inside your oven and preheat to 450°F (232°C) for at least 45 minutes. Invert your chilled dough onto a sheet of parchment paper, rub off excess flour, and make a decisive 1/4-inch deep slash along the length of the loaf using a razor blade angled at 30 degrees. Carefully lower the parchment into the screaming-hot Dutch oven, replace the lid, and bake for 20 minutes; then remove the lid and bake for another 20 to 25 minutes until deeply golden brown.",
        "tip": "Wait at least 2 hours before slicing into the bread; cutting hot bread causes steam to escape prematurely, leaving a gummy crumb.",
        "codeSnippet": null
      }
    ],
    "tags": [
      "sourdough",
      "bread baking",
      "artisan bread",
      "fermentation",
      "baking techniques"
    ],
    "sources": [
      {
        "title": "Naturally Leavened Sourdough Bread Recipe",
        "url": "https://www.kingarthurbaking.com/recipes/naturally-leavened-sourdough-bread-recipe",
        "domain": "kingarthurbaking.com",
        "type": "Official"
      },
      {
        "title": "A Beginner's Sourdough Bread Guide",
        "url": "https://www.theperfectloaf.com/beginners-sourdough-bread/",
        "domain": "theperfectloaf.com",
        "type": "Article"
      }
    ],
    "youtubeQuery": "beginner artisan sourdough bread step by step tutorial",
    "warnings": [
      "Cast iron Dutch ovens retain extreme heat (450°F+); always wear heavy-duty heat-resistant oven mitts when handling the pot or lid.",
      "Do not slice the bread while hot, as the internal structure continues setting while cooling and slicing early will result in a gummy texture."
    ],
    "cost": "$5-15",
    "id": "starter-cooking-food-0",
    "category": "Cooking & Food",
    "slug": "how-to-bake-artisan-sourdough-bread-from-scratch",
    "heroImage": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=500&fit=crop&auto=format",
    "popularity": 74,
    "published": "2026-09-17",
    "author": {
      "name": "WTS Editorial",
      "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=faces",
      "role": "How-To Expert"
    },
    "isFeatured": true
  },
  {
    "title": "How to Install Heavy-Duty Floating Shelves",
    "summary": "Learn how to securely mount floating shelves onto drywall and wall studs for a clean, modern aesthetic. Following these instructions ensures your shelves remain perfectly level and capable of holding books, plants, and heavy decor without sagging.",
    "difficulty": "Beginner",
    "estimatedTime": "1 to 2 hours",
    "tools": [
      "Stud finder",
      "Bubble level or 24-inch torpedo level",
      "Cordless drill with drill and driver bits",
      "Measuring tape and pencil",
      "Floating shelf kit (with internal bracket rods)",
      "Heavy-duty hollow-wall toggle anchors (if studs are missed)"
    ],
    "steps": [
      {
        "id": 1,
        "title": "Determine Placement and Mark Working Height",
        "content": "Select the wall area where you want your shelf to sit, taking into account eye level and surrounding furniture. Use a tape measure to mark your desired shelf height from the floor, making a small pencil mark at the center point. Hold the shelf or a long straightedge against the wall at this mark to visually confirm that clearance above and below looks proportionate. Ensure the chosen location avoids being obstructed by opening doors or window trim.",
        "tip": "Standard eye-level height for decorative shelving is typically between 54 and 60 inches from the finished floor.",
        "codeSnippet": null
      },
      {
        "id": 2,
        "title": "Locate and Mark Wall Studs",
        "content": "Turn on your electronic stud finder and slide it horizontally across the wall area, scanning several inches to the left and right of your height mark. When the tool alerts to a stud edge, mark it lightly with a pencil, then scan from the opposite direction to locate the other edge. Center your marks between those edges to pinpoint the exact 1.5-inch center of the wooden stud. Whenever possible, plan to drive mounting screws directly into at least one or two studs for maximum weight support.",
        "tip": "Tap a thin finishing nail into your pencil marks to physically confirm you strike solid wood before drilling larger holes.",
        "codeSnippet": null,
        "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&h=400&fit=crop&auto=format"
      },
      {
        "id": 3,
        "title": "Align and Level the Internal Mounting Bracket",
        "content": "Hold the metal concealed mounting bracket against the wall at your determined height. Place your bubble level on top of the bracket bar and adjust until the indicator bubble is centered between the lines. While holding the bracket firmly in place, use a pencil to trace the mounting screw holes directly onto the drywall. Mark holes directly over your detected wall studs, and select secondary hole locations on the bracket for drywall anchors if stud spacing does not align with every slot.",
        "tip": "Have a helper hold the level steady while you trace the holes to prevent the bracket from shifting.",
        "codeSnippet": null
      },
      {
        "id": 4,
        "title": "Drill Pilot Holes and Secure the Bracket",
        "content": "Set the bracket aside and drill pilot holes into the stud marks using a drill bit slightly narrower than your wood screws. For marks that fall in hollow drywall without studs, drill holes sized appropriately for toggle anchors or heavy-duty drywall anchors and insert the hardware. Reposition the bracket against the wall and drive the primary structural screws into the wall studs using your drill or impact driver. Finish by fastening the anchor screws tightly so the bracket sits completely flush and rigid against the drywall surface.",
        "tip": null,
        "codeSnippet": null
      },
      {
        "id": 5,
        "title": "Slide the Shelf Onto the Support Rods",
        "content": "Inspect the back of your wooden shelf to confirm the routered slots align cleanly with the bracket's protruding steel prongs. Align the shelf openings with the bracket rods and slide the shelf straight back toward the wall. If the fit is tight, gently tap the front edge of the shelf using a rubber mallet or your fist cushioned by a folded towel. Push the shelf completely back until the rear edge makes uniform contact with the wall face along its entire length.",
        "tip": "If the shelf jams halfway, check inside the pre-drilled holes for loose wood fibers or slight misalignments in bracket prong angles.",
        "codeSnippet": null
      },
      {
        "id": 6,
        "title": "Fasten Set Screws and Verify Load Stability",
        "content": "Look under the bottom face of the shelf for small pilot holes intended for locking set screws. Drive the provided small machine or wood screws up through the bottom of the shelf into the bracket rods to prevent the shelf from sliding forward over time. Place your level across the shelf surface from left to right and front to back to verify it does not tilt down. Apply firm downward hand pressure to verify the shelf is sturdy before styling it with your decor items.",
        "tip": "Distribute heavier items like ceramic planters and hardbound books closer to the wall edge rather than the front lip.",
        "codeSnippet": null
      }
    ],
    "tags": [
      "floating shelves",
      "home improvement",
      "diy shelving",
      "wall mounting",
      "interior decor"
    ],
    "sources": [
      {
        "title": "How to Hang Floating Shelves",
        "url": "https://www.thisoldhouse.com/storage-organization/21016629/how-to-hang-floating-shelves",
        "domain": "thisoldhouse.com",
        "type": "Article"
      },
      {
        "title": "How to Install Floating Shelves",
        "url": "https://www.homedepot.com/c/ah/how-to-install-floating-shelves/9ba683603be9fa5395fab90e7da3c0b",
        "domain": "homedepot.com",
        "type": "Official"
      },
      {
        "title": "How to Hang Shelves",
        "url": "https://www.familyhandyman.com/project/how-to-hang-shelves/",
        "domain": "familyhandyman.com",
        "type": "Article"
      }
    ],
    "youtubeQuery": "how to install floating shelves into wall studs and drywall",
    "warnings": [
      "Always check for electrical cables and plumbing pipes behind walls using a multi-scanner or stud finder with AC detection before drilling.",
      "Do not rely solely on standard plastic drywall anchors for shelves intended to carry heavy books or dishware; at least one anchor must penetrate a wall stud."
    ],
    "cost": "$30 - $120",
    "id": "starter-home-diy-1",
    "category": "Home & DIY",
    "slug": "how-to-install-heavy-duty-floating-shelves",
    "heroImage": "https://images.unsplash.com/photo-1513694203232-719a280e0f79?w=800&h=500&fit=crop&auto=format",
    "popularity": 91,
    "published": "2026-09-17",
    "author": {
      "name": "WTS Editorial",
      "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=faces",
      "role": "How-To Expert"
    },
    "isFeatured": false
  },
  {
    "title": "How to Fix a Leaky Cartridge or Ball Faucet",
    "summary": "Stop irritating water drips and lower your utility bill by replacing worn internal faucet seals or cartridges yourself. In under an hour, you will safely disassemble the faucet body, install fresh replacement parts, and restore a watertight seal.",
    "difficulty": "Beginner",
    "estimatedTime": "45 mins",
    "tools": [
      "Adjustable wrench",
      "Phillips and flathead screwdrivers",
      "Hex (Allen) key set",
      "Replacement faucet cartridge or O-ring kit",
      "Plumber's silicone grease",
      "Clean rag or small towel",
      "White vinegar and old toothbrush"
    ],
    "steps": [
      {
        "id": 1,
        "title": "Shut off the water supply and seal the drain",
        "content": "Look beneath the sink cabinet and locate the oval shutoff valves for both hot and cold water lines. Turn both valves clockwise until they are fully closed and turn the faucet handles on to release any trapped line pressure. Place a clean rag or towel over the sink basin drain to prevent dropped screws and tiny components from falling down the pipe.",
        "tip": "If the under-sink shutoff valves are stuck or corroded, shut off the main water shutoff valve to the entire house before proceeding.",
        "codeSnippet": null
      },
      {
        "id": 2,
        "title": "Remove the faucet handle",
        "content": "Use a flathead screwdriver or utility knife edge to gently pry off the decorative index cap on top of or behind the handle. Locate the exposed screw underneath, which will typically require either a Phillips screwdriver or an Allen wrench to loosen. Unscrew the fastener completely, lift the handle straight off the faucet stem, and set the parts aside in order.",
        "tip": "If the handle is stuck due to mineral buildup, wrap a warm, vinegar-soaked cloth around the joint for 10 minutes to dissolve deposits.",
        "codeSnippet": null,
        "image": "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=700&h=400&fit=crop&auto=format"
      },
      {
        "id": 3,
        "title": "Remove the bonnet nut and retaining clip",
        "content": "Unthread any decorative chrome collar sleeve by hand to expose the brass bonnet nut or retaining mechanism underneath. Using an adjustable wrench, turn the retaining nut counterclockwise while firmly stabilizing the faucet spout with your other hand to avoid twisting the fixture. If working with a Moen-style faucet, use needle-nose pliers to pull the brass U-shaped retaining clip straight out horizontally.",
        "tip": "Tape the jaws of your adjustable wrench with electrical tape to avoid scratching decorative chrome or matte finishes.",
        "codeSnippet": null
      },
      {
        "id": 4,
        "title": "Extract the cartridge or stem assembly",
        "content": "Grasp the stem of the cartridge with a pair of pliers and pull straight up with steady, firm pressure to dislodge it from the valve body. Note the exact orientation of the cartridge—especially any tabs, notches, or flat edges that align with the faucet housing. If your faucet uses traditional compression stems, pull out the stem and inspect the rubber seat washer and spring seated deep inside the valve recess.",
        "tip": "Take a quick photo of the cartridge orientation on your phone before removing it to ensure you insert the new one facing the right direction.",
        "codeSnippet": null
      },
      {
        "id": 5,
        "title": "Clean mineral deposits from the valve body",
        "content": "Dip an old toothbrush into distilled white vinegar and scrub the interior brass walls of the valve cavity thoroughly. Flush out any loose mineral flakes, calcium scale, and old debris using a damp rag. Smooth, clean interior walls are critical to guarantee that the new rubber gaskets seat tightly against the metal housing without leaking.",
        "tip": "Check the interior valve walls for pitting or deep grooves; severe pitting may prevent a new seal and require whole faucet replacement.",
        "codeSnippet": null
      },
      {
        "id": 6,
        "title": "Install the replacement cartridge and seals",
        "content": "Apply a thin layer of food-grade silicone plumber's grease to the rubber O-rings and seals on the new replacement cartridge. Slide the new cartridge down into the valve housing, rotating it gently until the alignment tabs click into the corresponding slots in the faucet body. If you removed a retaining clip earlier, slide it back into its slot completely to lock the cartridge in place.",
        "tip": "Never use petroleum jelly (Vaseline) instead of plumber's grease, as petroleum breaks down rubber gaskets over time.",
        "codeSnippet": null
      },
      {
        "id": 7,
        "title": "Reassemble the faucet and test for leaks",
        "content": "Thread the bonnet nut back on and tighten it with your adjustable wrench until snug, being careful not to overtighten. Reattach the handle, tighten the set screw, and snap the decorative cap back into place. Slowly turn both under-sink shutoff valves counterclockwise to restore water pressure, remove the drain towel, and run the tap for 60 seconds to purge trapped air and verify the drip is resolved.",
        "tip": null,
        "codeSnippet": null
      }
    ],
    "tags": [
      "plumbing",
      "home improvement",
      "diy repairs",
      "faucet repair",
      "water conservation"
    ],
    "sources": [
      {
        "title": "How to Fix a Dripping Faucet - This Old House",
        "url": "https://www.thisoldhouse.com/plumbing/21015568/how-to-fix-a-dripping-faucet",
        "domain": "thisoldhouse.com",
        "type": "Article"
      },
      {
        "title": "How to Fix a Leaky Faucet - The Home Depot",
        "url": "https://www.homedepot.com/c/ah/how-to-fix-a-dripping-faucet/9ba68403fb9dd6a30c00dbf83c84d72",
        "domain": "homedepot.com",
        "type": "Official"
      },
      {
        "title": "Fix a Leaking Single Handle Faucet - Family Handyman",
        "url": "https://www.familyhandyman.com/project/how-to-repair-a-kitchen-faucet/",
        "domain": "familyhandyman.com",
        "type": "Article"
      }
    ],
    "youtubeQuery": "how to fix a leaky cartridge faucet step by step",
    "warnings": [
      "Always turn off the water supply and verify it is completely dead before removing any faucet components.",
      "Do not overtighten brass nuts or plastic cartridges, as excessive force will crack the components or strip threads."
    ],
    "cost": "$10-30",
    "id": "starter-home-diy-2",
    "category": "Home & DIY",
    "slug": "how-to-fix-a-leaky-cartridge-or-ball-faucet",
    "heroImage": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format",
    "popularity": 92,
    "published": "2026-09-17",
    "author": {
      "name": "WTS Editorial",
      "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=faces",
      "role": "How-To Expert"
    },
    "isFeatured": false
  },
  {
    "title": "How to Draw a Realistic Pencil Portrait from a Photo Reference",
    "summary": "Learn how to accurately translate a reference photo into a lifelike graphite portrait using proven proportional guidelines and layering techniques. This step-by-step method guides you from initial structural mapping to deep tonal shading and delicate final highlights.",
    "difficulty": "Intermediate",
    "estimatedTime": "3-5 hours",
    "tools": [
      "Graphite pencil set (grades 2H, HB, 2B, 4B, 6B)",
      "Heavyweight drawing paper or Bristol board (vellum surface)",
      "Kneaded eraser and precision mechanical eraser",
      "Blending stump (tortillon) or soft tissue",
      "Clear ruler with fine measurement markings",
      "High-resolution printed reference photo (preferably black and white)"
    ],
    "steps": [
      {
        "id": 1,
        "title": "Prepare and grid your reference photo",
        "content": "Convert your reference photo to black and white on your computer or phone to isolate value patterns without color distractions. Print the photo to the exact size you intend to draw, or calculate a 1:1 or 2:1 ratio for enlargement. Use a clear ruler and fine pen to draw a 1-inch (or 2-centimeter) grid over the entire printed image, numbering each column and row along the borders for quick reference.",
        "tip": "Increasing the contrast on your reference photo before printing makes shadow edges and highlight boundaries much easier to see.",
        "codeSnippet": null
      },
      {
        "id": 2,
        "title": "Transfer the grid to your drawing surface",
        "content": "Replicate the exact grid proportions onto your drawing paper using an ultra-light touch with a 2H pencil. Ensure your grid lines are completely straight and square, as any distortion in the grid will directly warp facial proportions. Label the grid coordinates along the edge of your paper identically to the reference. Keep these lines faint so they can be erased cleanly later without leaving indentations.",
        "tip": "Use a light hand; pressing hard with a hard pencil like 2H can permanently groove the paper fibers.",
        "codeSnippet": null,
        "image": "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=700&h=400&fit=crop&auto=format"
      },
      {
        "id": 3,
        "title": "Block in major contour lines and facial landmarks",
        "content": "Working square by square, sketch the general outline of the head, jawline, ears, and hairline with an HB pencil. Plot landmark points where the pupils, nose base, and lip line intersect the grid lines to establish correct placement. Focus purely on line positions and shapes rather than shading at this stage. Step back frequently to compare the overall silhouette with your photo.",
        "tip": "Turn both your photo and drawing upside down periodically; this disrupts your brain's assumptions and lets you spot proportional errors purely as abstract shapes.",
        "codeSnippet": null
      },
      {
        "id": 4,
        "title": "Map shadow shapes and erase grid lines",
        "content": "Lightly trace the boundaries of core shadows, cast shadows, and dark value areas, such as the eye sockets, under-nose shadow, and jawline drop shadow. Once your structural lines and shadow boundaries are established, take a kneaded eraser and gently lift away the remaining visible grid lines. Blot the pencil marks gently rather than rubbing vigorously to preserve the paper texture.",
        "tip": "Treat shadows as solid two-dimensional puzzle pieces before applying tone, outlining where the dark zones meet the midtones.",
        "codeSnippet": null
      },
      {
        "id": 5,
        "title": "Establish midtones and soft transitions",
        "content": "Begin shading the midtone zones using an HB or 2B pencil applied in smooth, consistent circular or cross-hatching motions. Build tone gradually from light to dark rather than trying to achieve final darkness on the first pass. Use a blending stump or folded tissue to soften transitions across smooth skin areas like the cheeks and forehead, smoothing gradations toward highlight areas.",
        "tip": "Never blend using your bare fingers; natural skin oils transfer to the paper and create permanent, blotchy patches that resist graphite.",
        "codeSnippet": null
      },
      {
        "id": 6,
        "title": "Render dark values and facial features",
        "content": "Switch to softer pencils (4B and 6B) to deepen the darkest areas: the pupils, inner corners of the lips, nostrils, and deep hair shadows. Render the irises with radial strokes and refine eyelashes with flicking motions starting thick at the root and tapering toward the tip. Sharpen feature edges against soft background tones to make the face visually pop forward.",
        "tip": "Leave the whites of the eyes slightly shaded; only pure specular reflections on moist surfaces should remain clean white paper.",
        "codeSnippet": null
      },
      {
        "id": 7,
        "title": "Lift highlights and add fine textures",
        "content": "Use a precision mono zero or cleanly cut kneaded eraser to pick out crisp specular highlights on the cornea, tip of the nose, and lower lip. Add fine surface textures such as eyebrow hairs, subtle lip creases, and individual flyaway hair strands with a freshly sharpened 2B pencil. Step back across the room to evaluate the total contrast balance, darkening weak shadows and cleaning any smudges around the perimeter.",
        "tip": "Lightly dab a kneaded eraser across overly dark cheek areas to seamlessly brighten the plane of the face without creating harsh edges.",
        "codeSnippet": null
      }
    ],
    "tags": [
      "drawing",
      "portraiture",
      "graphite-sketching",
      "art-tutorial",
      "grid-method",
      "realism"
    ],
    "sources": [
      {
        "title": "Proko: How to Draw a Portrait from a Photo",
        "url": "https://www.proko.com/course/how-to-draw-portrait-from-photo",
        "domain": "proko.com",
        "type": "Article"
      },
      {
        "title": "RapidFireArt: How to Draw a Face from a Photo",
        "url": "https://rapidfireart.com/2017/04/18/how-to-draw-a-face-from-a-photo-for-beginners/",
        "domain": "rapidfireart.com",
        "type": "Article"
      },
      {
        "title": "Artists Network: Pencil Portrait Drawing Step by Step",
        "url": "https://www.artistsnetwork.com/art-mediums/drawing/pencil-portrait-drawing-step-by-step/",
        "domain": "artistsnetwork.com",
        "type": "Article"
      }
    ],
    "youtubeQuery": "how to draw a realistic portrait from a photo step by step graphite pencil",
    "warnings": [
      "Keep a clean sheet of scrap paper under your drawing hand to avoid smudging delicate shading across the paper surface.",
      "Avoid applying heavy pressure with hard-lead pencils (2H and harder), which can permanently dent and score drawing paper."
    ],
    "cost": "$15-30",
    "id": "starter-creative-art-3",
    "category": "Creative & Art",
    "slug": "how-to-draw-a-realistic-pencil-portrait-from-a-photo-reference",
    "heroImage": "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&h=500&fit=crop&auto=format",
    "popularity": 90,
    "published": "2026-09-17",
    "author": {
      "name": "WTS Editorial",
      "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=faces",
      "role": "How-To Expert"
    },
    "isFeatured": false
  },
  {
    "title": "Beginner's Guide to Essential Watercolor Techniques",
    "summary": "Master the core foundation of watercolor painting by exploring fundamental brush and wash methods on paper. By the end of this guide, you will understand pigment-to-water ratios and be able to execute flat washes, soft blends, and realistic textures with confidence.",
    "difficulty": "Beginner",
    "estimatedTime": "1.5 hours",
    "tools": [
      "Cold-press 140 lb (300 gsm) watercolor paper",
      "Round watercolor brushes (sizes #4 and #8)",
      "Watercolor paint set (tubes or half-pans)",
      "Two containers of clean water",
      "Absorbent paper towels or cotton rag",
      "Painter's masking tape and a firm backing board"
    ],
    "steps": [
      {
        "id": 1,
        "title": "Prepare your workstation and paper surface",
        "content": "Secure all four edges of a sheet of 140 lb cold-press paper to your backing board using painter's tape to prevent buckling as it dries. Set out two jars of water side by side: one for rinsing pigment out of your brush, and the second for picking up clean water. Wake up your watercolor pans by placing a drop of clean water onto each color well using a brush or a spray bottle roughly two minutes before painting.",
        "tip": "Tape borders roughly 1/4 inch into the paper edge to create a clean, crisp frame around your finished exercises.",
        "codeSnippet": null
      },
      {
        "id": 2,
        "title": "Execute a flat wash using wet-on-dry application",
        "content": "Mix a generous puddle of paint on your palette until it reaches the consistency of whole milk. Tilt your board slightly at a 15-degree angle, load your #8 brush fully, and paint a continuous horizontal stroke across the dry paper, allowing a bead of liquid paint to collect along the bottom edge of the stroke. Reload your brush and place the next stroke directly overlapping that bead, pulling the paint downward in overlapping passes until you complete an even, streak-free square.",
        "tip": "Never go back into a wet wash that has begun to settle, or you will create blotchy backruns called 'blooms' or 'cauliflowers'.",
        "codeSnippet": null,
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=700&h=400&fit=crop&auto=format"
      },
      {
        "id": 3,
        "title": "Blend color softly using the wet-on-wet technique",
        "content": "Rinse your brush thoroughly and paint a square of clean water onto the paper until the surface exhibits a subtle satin sheen without deep standing pools. Dip your brush into saturated pigment and gently touch the tip to the center of the damp patch. Observe how the pigment naturally disperses and feathers outward through the water film, creating soft, atmospheric edges without hard lines.",
        "tip": "If the paper looks dull and no longer reflects light, it has dried too much; let it dry completely before re-wetting to avoid damaging the paper fibers.",
        "codeSnippet": null
      },
      {
        "id": 4,
        "title": "Create a seamless graded wash",
        "content": "Begin by laying down a single saturated stroke of paint at the top of your paper just as you did for the flat wash. Before making the second stroke, dip only the tip of your brush into clean water, blot it lightly once against your rag, and pull down the bead from the first stroke. Continue down the section, dipping in clean water before each pass so the tone gradually fades from intense pigment to clear water.",
        "tip": "Graded washes are ideal for painting realistic skies, atmospheric depth, and lighting transitions.",
        "codeSnippet": null
      },
      {
        "id": 5,
        "title": "Produce broken texture with dry brush strokes",
        "content": "Pick up thick, relatively dry paint straight from the pan or palette with minimal water on your brush. Blot the belly of the brush firmly against a dry paper towel to strip away residual moisture until the bristles are slightly splayed. Skim the brush across the paper rapidly at a shallow 30-degree angle, allowing the pigment to catch only the high ridges of the textured cold-press paper.",
        "tip": "Use this technique to easily render tree bark, rough stone surfaces, or light glittering on choppy water.",
        "codeSnippet": null
      },
      {
        "id": 6,
        "title": "Practice lifting pigment to reclaim highlights",
        "content": "Rinse your brush clean and firmly squeeze out all water using a paper towel so the bristles are merely damp, forming a 'thirsty brush'. While a painted area is still damp, press and drag the thirsty brush across the paint to draw pigment off the page and reveal lighter undertones. For paint that has already dried, scrub gently with damp, stiff bristles and immediately dab the spot with a dry paper towel to lift color.",
        "tip": "Some staining pigments like Phthalo Blue or Alizarin Crimson penetrate paper fibers deeply and resist lifting, whereas sedimentary pigments lift easily.",
        "codeSnippet": null
      }
    ],
    "tags": [
      "Watercolor",
      "Painting Basics",
      "Art Techniques",
      "Wash Techniques",
      "Fine Art"
    ],
    "sources": [
      {
        "title": "Winsor & Newton Watercolor Guides",
        "url": "https://www.winsornewton.com/na/masterclass/essential-watercolour-techniques/",
        "domain": "winsornewton.com",
        "type": "Official"
      },
      {
        "title": "The Spruce Crafts: Basic Watercolor Techniques",
        "url": "https://www.thesprucecrafts.com/basic-watercolor-techniques-2578794",
        "domain": "thesprucecrafts.com",
        "type": "Article"
      },
      {
        "title": "Jackson's Art: A Guide to Watercolor Painting for Beginners",
        "url": "https://www.jacksonsart.com/blog/2020/05/21/watercolour-painting-for-beginners/",
        "domain": "jacksonsart.com",
        "type": "Article"
      }
    ],
    "youtubeQuery": "basic watercolor techniques for beginners wet on wet dry brush wash",
    "warnings": [
      "Standard sketchbook or printer paper will warp, pill, and tear when saturated; always use watercolor paper designed for wet media.",
      "Never leave your brushes standing bristle-down in water jars, as this permanently bends the brush hairs and loosens the ferrule adhesive."
    ],
    "cost": "$25-$45",
    "id": "starter-creative-art-4",
    "category": "Creative & Art",
    "slug": "beginner-s-guide-to-essential-watercolor-techniques",
    "heroImage": "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=500&fit=crop&auto=format",
    "popularity": 94,
    "published": "2026-09-17",
    "author": {
      "name": "WTS Editorial",
      "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=faces",
      "role": "How-To Expert"
    },
    "isFeatured": false
  },
  {
    "title": "Build a REST API with Node.js and Express",
    "summary": "Learn how to build a fully functional, production-ready RESTful API using Node.js and Express from scratch. You will implement complete CRUD operations, request validation, proper HTTP status codes, and centralized error handling.",
    "difficulty": "Beginner",
    "estimatedTime": "45 mins",
    "tools": [
      "Node.js (v18 or higher)",
      "npm (Node Package Manager)",
      "Visual Studio Code (or any code editor)",
      "Postman or cURL",
      "Express.js framework"
    ],
    "steps": [
      {
        "id": 1,
        "title": "Initialize the Project and Install Dependencies",
        "content": "Create a new directory for your API and initialize it using npm init with default settings. Next, install Express as your production dependency for routing and HTTP handling. Install nodemon as a development dependency so your server restarts automatically whenever file changes are detected. Finally, add a development start script to your package.json file.",
        "tip": "Set \"type\": \"commonjs\" or omit the field in package.json if you prefer using require syntax, or set it to \"module\" for ES imports.",
        "codeSnippet": "mkdir node-rest-api && cd node-rest-api\nnpm init -y\nnpm install express\nnpm install -D nodemon"
      },
      {
        "id": 2,
        "title": "Create the Core Server Entry Point",
        "content": "Create an entry file named server.js in your project's root folder. Import Express, instantiate the application, and configure your listener on port 3000 or an environment variable. Add a simple health-check route at the root path to verify that the server receives and answers HTTP requests properly. Run your dev script to confirm that the server boots up without runtime errors.",
        "tip": "Always use process.env.PORT || 3000 to allow cloud hosting providers like Render or AWS to assign their own port dynamically.",
        "codeSnippet": "const express = require('express');\nconst app = express();\nconst PORT = process.env.PORT || 3000;\n\napp.use(express.json());\n\napp.get('/', (req, res) => {\n  res.json({ message: 'API is running successfully' });\n});\n\napp.listen(PORT, () => {\n  console.log(`Server listening on port ${PORT}`);\n});",
        "image": "https://images.unsplash.com/photo-1555066931-bf19f8fd1085?w=700&h=400&fit=crop&auto=format"
      },
      {
        "id": 3,
        "title": "Implement GET Routes for Reading Data",
        "content": "Define an in-memory array of sample objects to serve as your temporary datastore. Implement an app.get route for /api/items that returns the full list of items with an HTTP 200 status code. Then, create a parameterized route /api/items/:id to look up an individual item by its unique identifier. Ensure you parse req.params.id into an integer and return an HTTP 404 response if the item cannot be found.",
        "tip": "Remember that route parameters extracted from req.params are strings by default; convert them to numbers using parseInt() or Number() before comparing.",
        "codeSnippet": "let items = [\n  { id: 1, name: 'Sample Item 1', price: 29.99 },\n  { id: 2, name: 'Sample Item 2', price: 49.99 }\n];\n\napp.get('/api/items', (req, res) => {\n  res.status(200).json(items);\n});\n\napp.get('/api/items/:id', (req, res) => {\n  const item = items.find(i => i.id === parseInt(req.params.id));\n  if (!item) return res.status(404).json({ error: 'Item not found' });\n  res.status(200).json(item);\n});"
      },
      {
        "id": 4,
        "title": "Implement the POST Route for Creating Data",
        "content": "Define an app.post route on /api/items to allow clients to create new records. Read the payload from req.body and validate that all required fields are present and valid before saving. Generate an auto-incremented or timestamp-based ID, construct the new record, and append it to your data array. Conclude by sending an HTTP 201 Created status along with the newly created resource.",
        "tip": "Never trust client-supplied input; perform strict checks on data types to prevent malformed data from polluting your datastore.",
        "codeSnippet": "app.post('/api/items', (req, res) => {\n  const { name, price } = req.body;\n  if (!name || typeof price !== 'number') {\n    return res.status(400).json({ error: 'Valid name and numeric price are required' });\n  }\n\n  const newItem = {\n    id: items.length ? items[items.length - 1].id + 1 : 1,\n    name,\n    price\n  };\n\n  items.push(newItem);\n  res.status(201).json(newItem);\n});"
      },
      {
        "id": 5,
        "title": "Implement PUT and DELETE Routes",
        "content": "Create an app.put route on /api/items/:id to handle item updates by locating the target item index. If the item exists, update its properties with the supplied req.body values and return the updated object with status 200. Next, create an app.delete route on /api/items/:id to remove items using the splice method or array filtering. Return an HTTP 204 No Content response upon successful deletion, or a 404 if the item ID does not exist.",
        "tip": "HTTP 204 responses must not contain a message body; use res.status(204).send() instead of res.json().",
        "codeSnippet": "app.put('/api/items/:id', (req, res) => {\n  const id = parseInt(req.params.id);\n  const itemIndex = items.findIndex(i => i.id === id);\n  if (itemIndex === -1) return res.status(404).json({ error: 'Item not found' });\n\n  const { name, price } = req.body;\n  items[itemIndex] = { id, name: name || items[itemIndex].name, price: price ?? items[itemIndex].price };\n  res.status(200).json(items[itemIndex]);\n});\n\napp.delete('/api/items/:id', (req, res) => {\n  const id = parseInt(req.params.id);\n  const exists = items.some(i => i.id === id);\n  if (!exists) return res.status(404).json({ error: 'Item not found' });\n\n  items = items.filter(i => i.id !== id);\n  res.status(204).send();\n});"
      },
      {
        "id": 6,
        "title": "Add Centralized Error Handling and 404 Middleware",
        "content": "Add a fallback route handler at the bottom of your file to capture requests made to nonexistent endpoints. Directly below the 404 handler, declare a global error-handling middleware function that accepts four arguments: err, req, res, and next. Log the error details to your terminal for debugging purposes during development. Return a standardized JSON payload with a 500 Internal Server Error status to avoid leaking internal stack traces to the client.",
        "tip": "Express identifies error-handling middleware specifically by the presence of four arguments (err, req, res, next). Omitting next will cause Express to treat it as standard middleware.",
        "codeSnippet": "// 404 Handler\napp.use((req, res, next) => {\n  res.status(404).json({ error: 'Route not found' });\n});\n\n// Global Error Handler\napp.use((err, req, res, next) => {\n  console.error(err.stack);\n  res.status(500).json({ error: 'An unexpected server error occurred' });\n});"
      },
      {
        "id": 7,
        "title": "Test All Endpoints Using Postman or cURL",
        "content": "Start your server using npm run dev and prepare your testing tool to verify each CRUD endpoint. Execute GET requests to verify both full collection and individual resource retrieval. Send POST, PUT, and DELETE requests using JSON payloads, verifying that status codes 201, 200, and 204 match your expectations. Test boundary scenarios, such as submitting missing fields or requesting nonexistent IDs, to verify your error handling.",
        "tip": "When making POST or PUT requests with cURL or Postman, ensure the Content-Type header is explicitly set to application/json.",
        "codeSnippet": "# Test GET all items\ncurl -X GET http://localhost:3000/api/items\n\n# Test POST new item\ncurl -X POST http://localhost:3000/api/items \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"name\": \"Wireless Mouse\", \"price\": 24.99}'"
      }
    ],
    "tags": [
      "Node.js",
      "Express.js",
      "REST API",
      "Backend Development",
      "JavaScript"
    ],
    "sources": [
      {
        "title": "Express.js Routing Guide",
        "url": "https://expressjs.com/en/guide/routing.html",
        "domain": "expressjs.com",
        "type": "Official"
      },
      {
        "title": "Node.js Official Documentation",
        "url": "https://nodejs.org/en/docs",
        "domain": "nodejs.org",
        "type": "Official"
      },
      {
        "title": "HTTP Response Status Codes - MDN Web Docs",
        "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
        "domain": "developer.mozilla.org",
        "type": "Documentation"
      }
    ],
    "youtubeQuery": "Node.js Express REST API tutorial for beginners",
    "warnings": [
      "In-memory arrays reset whenever the server restarts; use a database like MongoDB or PostgreSQL for persistent production data.",
      "Do not expose detailed error stack traces to clients in production environments, as they can reveal system architecture vulnerabilities."
    ],
    "cost": "Free",
    "id": "starter-tech-programming-5",
    "category": "Tech & Programming",
    "slug": "build-a-rest-api-with-node-js-and-express",
    "heroImage": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=500&fit=crop&auto=format",
    "popularity": 94,
    "published": "2026-09-17",
    "author": {
      "name": "WTS Editorial",
      "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=faces",
      "role": "How-To Expert"
    },
    "isFeatured": false
  },
  {
    "title": "How to Build a Realistic Personal Budget from Scratch",
    "summary": "Learn how to track your cash flow, prioritize essential expenses, and allocate savings using a proven budgeting framework. By following this step-by-step guide, you will gain full control over your day-to-day spending and make steady progress toward your financial goals.",
    "difficulty": "Beginner",
    "estimatedTime": "60-90 mins",
    "tools": [
      "Spreadsheet software (Google Sheets or Microsoft Excel)",
      "Last 3 months of bank and credit card statements",
      "Recent pay stubs or proof of all income sources",
      "Calculator",
      "Free budgeting app (optional, e.g., Empower, YNAB trial, or Mint alternative)"
    ],
    "steps": [
      {
        "id": 1,
        "title": "Calculate your net monthly income",
        "content": "Gather your recent pay stubs, direct deposit records, and any documentation of secondary income like freelance work, dividends, or side hustles. Calculate your net take-home pay, which is the actual amount deposited into your bank account after taxes, 401(k) contributions, and healthcare deductions. If your income fluctuates, take the average of your lowest three earning months over the past year to establish a conservative baseline. Write this final baseline figure down at the top of your budgeting sheet as your starting monthly limit.",
        "tip": "Never build your budget around gross income, as doing so will cause you to overestimate your available cash by 20% to 30%.",
        "codeSnippet": null
      },
      {
        "id": 2,
        "title": "Audit past spending from statements",
        "content": "Download your bank and credit card statements covering the previous 90 days. Go line by line and assign each transaction to a basic category such as housing, groceries, dining out, utilities, transportation, and discretionary shopping. Total each category per month and calculate the three-month average to uncover your real spending habits rather than idealized guesses. This historical baseline prevents you from setting unrealistically low targets that cause budget burnout.",
        "tip": "Pay close attention to forgotten recurring subscription charges like streaming platforms and app memberships, which can quickly add up.",
        "codeSnippet": null,
        "image": "https://images.unsplash.com/photo-1517971129774-8a2b38fa128e?w=700&h=400&fit=crop&auto=format"
      },
      {
        "id": 3,
        "title": "Select an appropriate budgeting framework",
        "content": "Select a structural model that aligns with your personality and financial situation. A popular starting point is the 50/30/20 rule, which directs 50% of net income toward essential needs, 30% toward discretionary wants, and 20% toward debt repayment and savings. Alternatively, consider zero-based budgeting if you prefer granular control, where every dollar is assigned a job until your income minus expenses equals zero. Choose the framework that feels sustainable for your lifestyle rather than the most mathematically complex one.",
        "tip": "If high-interest debt exceeds 20% of your income, temporarily adjust the 50/30/20 proportions to 50/20/30 to prioritize aggressive repayment.",
        "codeSnippet": null
      },
      {
        "id": 4,
        "title": "List and lock in fixed expenses",
        "content": "Document all non-negotiable, fixed expenses that remain identical or near-identical each month. These typically include rent or mortgage payments, auto loans, student debt minimums, insurance premiums, and basic internet access. Subtract the sum of these fixed obligations directly from your net monthly income to reveal your remaining disposable pool for flexible expenses. Because these bills are predictable, set up automated payments through your bank to ensure you never incur late fees.",
        "tip": "Audit insurance policies and internet bills annually by calling providers to negotiate rates or compare competing offers.",
        "codeSnippet": null
      },
      {
        "id": 5,
        "title": "Set realistic caps on variable spending",
        "content": "Allocate remaining funds across variable expense categories such as groceries, fuel, household supplies, entertainment, and dining out. Base these figures on the averages calculated during your 90-day statement audit, reducing non-essential targets incrementally rather than slashing them drastically. Give yourself a small miscellaneous buffer of $50 to $100 for minor unexpected expenses that arise throughout the month. Ensure that total fixed expenses plus total variable allocations do not exceed your net monthly income.",
        "tip": "Try cutting discretionary categories by just 10% to 15% in your first month rather than eliminating them entirely.",
        "codeSnippet": null
      },
      {
        "id": 6,
        "title": "Automate savings and emergency fund transfers",
        "content": "Treat your savings and debt elimination contributions as compulsory bills rather than afterthoughts. Schedule an automatic bank transfer on the day following each payday to move savings directly into a separate High-Yield Savings Account (HYSA). Prioritize building a beginner emergency fund of $1,000 to cover minor crises without turning to credit cards, then scale toward 3 to 6 months of living expenses. Once emergency reserves are funded, redirect automated contributions toward investments or accelerated principal debt paydown.",
        "tip": "Keeping your emergency fund in a separate bank reduces the temptation to dip into it for casual purchases.",
        "codeSnippet": null
      },
      {
        "id": 7,
        "title": "Schedule a recurring weekly review and monthly reset",
        "content": "Block out 10 to 15 minutes on your calendar every Sunday to log recent transactions and compare current spending against category caps. Weekly micro-reviews allow you to adjust spending mid-month if you notice you have consumed most of your dining budget early on. At the end of the calendar month, tally final figures, analyze any overspending variances without judgment, and roll surpluses into savings or debt repayment. Tweak your category targets for the upcoming month to reflect upcoming seasonal expenses, holidays, or utility rate changes.",
        "tip": "Expect your first two to three budgets to require substantial adjustments before you find an effortless rhythm.",
        "codeSnippet": null
      }
    ],
    "tags": [
      "Personal Finance",
      "Budgeting",
      "Money Management",
      "Financial Planning",
      "Savings"
    ],
    "sources": [
      {
        "title": "Making a Budget",
        "url": "https://consumer.ftc.gov/articles/making-budget",
        "domain": "consumer.ftc.gov",
        "type": "Official"
      },
      {
        "title": "How to Create a Budget: Step-by-Step Guide",
        "url": "https://www.nerdwallet.com/article/finance/how-to-budget",
        "domain": "nerdwallet.com",
        "type": "Article"
      },
      {
        "title": "An Essential Guide to Building an Emergency Fund",
        "url": "https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/",
        "domain": "consumerfinance.gov",
        "type": "Official"
      }
    ],
    "youtubeQuery": "how to create a personal budget step by step spreadsheet",
    "warnings": [
      "Do not base calculations on gross salary, as forgetting taxes and payroll deductions will create an immediate deficit.",
      "Avoid setting overly restrictive targets in month one; drastic lifestyle cuts frequently cause budget fatigue and abandonment."
    ],
    "cost": "Free",
    "id": "starter-finance-productivity-6",
    "category": "Finance & Productivity",
    "slug": "how-to-build-a-realistic-personal-budget-from-scratch",
    "heroImage": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&h=500&fit=crop&auto=format",
    "popularity": 77,
    "published": "2026-09-17",
    "author": {
      "name": "WTS Editorial",
      "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=faces",
      "role": "How-To Expert"
    },
    "isFeatured": false
  }
];
